# This workflow will build, publish and push a .NET project docker image
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./MythicalBeasts-API/MythicalBeasts-API.sln
    - name: Build
      run: dotnet build ./MythicalBeasts-API/MythicalBeasts-API.sln --no-restore
    - name: Test
      run: dotnet test ./MythicalBeasts-API/MythicalBeasts-API.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./MythicalBeasts-API/MythicalBeasts-API.sln /p:PublishProfile=DefaultContainer
    - name: Build Docker Image
      working-directory: MythicalBeasts-API/mythicalbeasts-api
      run: docker build . -t imshelledin21/mythicalbeasts:latest

